version: "3.7"

services:
  traefik:
    ports:
      - "443:443"
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  api:
    labels:
      - "traefik.frontend.rule=Host:api.miraris.moe"
