version: "3.7"

services:
  mongo:
    image: mongo
    env_file:
      - mongo.env
    secrets:
      - mongo-root-username
      - mongo-root-password

  worker:
    image: miraris/lineart-worker:latest
    env_file:
      - mongo.env

secrets:
  mongo-root-username:
    external: true
  mongo-root-password:
    external: true
