version: "3.7"

# TODO: separate networks

services:
  mongo:
    image: mongo

  worker:
    image: miraris/lineart-worker:latest
    env_file: 
      - worker.env

  api:
    image: miraris/lineart-api:latest
    ports:
      - "3000:3000"
